/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MediaType = IDL.Variant({
  'video' : IDL.Null,
  'photo' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'createdAt' : IDL.Int,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'coverPhoto' : IDL.Opt(ExternalBlob),
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'postId' : IDL.Nat64,
});
export const Post = IDL.Record({
  'id' : IDL.Nat64,
  'media' : ExternalBlob,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'caption' : IDL.Text,
  'mediaType' : MediaType,
});
export const NotificationType = IDL.Variant({
  'newPostFromFriend' : IDL.Null,
  'friendRequestAccepted' : IDL.Null,
  'friendRequestReceived' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'notificationType' : NotificationType,
  'createdAt' : IDL.Int,
  'read' : IDL.Bool,
  'user' : IDL.Principal,
  'relatedUser' : IDL.Opt(IDL.Principal),
  'postId' : IDL.Opt(IDL.Nat64),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'addComment' : IDL.Func([IDL.Nat64, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([IDL.Text, ExternalBlob, MediaType], [IDL.Nat64], []),
  'declineFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'deleteComment' : IDL.Func([IDL.Nat64, IDL.Nat], [], []),
  'deletePost' : IDL.Func([IDL.Nat64], [], []),
  'editPost' : IDL.Func([IDL.Nat64, IDL.Text], [], []),
  'getAcceptedFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Nat64], [IDL.Vec(Comment)], ['query']),
  'getLikes' : IDL.Func([IDL.Nat64], [IDL.Vec(IDL.Principal)], ['query']),
  'getMainFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPendingFriendRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getPostById' : IDL.Func([IDL.Nat64], [Post], ['query']),
  'getPrincipalByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'getProfileByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getProfilePosts' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getSentFriendRequests' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat64], [], []),
  'markAllNotificationsAsRead' : IDL.Func([], [], []),
  'register' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeFriend' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'updateBio' : IDL.Func([IDL.Text], [], []),
  'updateCoverPhoto' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
  'updateProfilePhoto' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MediaType = IDL.Variant({ 'video' : IDL.Null, 'photo' : IDL.Null });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'createdAt' : IDL.Int,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'coverPhoto' : IDL.Opt(ExternalBlob),
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'postId' : IDL.Nat64,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat64,
    'media' : ExternalBlob,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'caption' : IDL.Text,
    'mediaType' : MediaType,
  });
  const NotificationType = IDL.Variant({
    'newPostFromFriend' : IDL.Null,
    'friendRequestAccepted' : IDL.Null,
    'friendRequestReceived' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'notificationType' : NotificationType,
    'createdAt' : IDL.Int,
    'read' : IDL.Bool,
    'user' : IDL.Principal,
    'relatedUser' : IDL.Opt(IDL.Principal),
    'postId' : IDL.Opt(IDL.Nat64),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'addComment' : IDL.Func([IDL.Nat64, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func(
        [IDL.Text, ExternalBlob, MediaType],
        [IDL.Nat64],
        [],
      ),
    'declineFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'deleteComment' : IDL.Func([IDL.Nat64, IDL.Nat], [], []),
    'deletePost' : IDL.Func([IDL.Nat64], [], []),
    'editPost' : IDL.Func([IDL.Nat64, IDL.Text], [], []),
    'getAcceptedFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Nat64], [IDL.Vec(Comment)], ['query']),
    'getLikes' : IDL.Func([IDL.Nat64], [IDL.Vec(IDL.Principal)], ['query']),
    'getMainFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPendingFriendRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getPostById' : IDL.Func([IDL.Nat64], [Post], ['query']),
    'getPrincipalByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getProfileByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getProfilePosts' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getSentFriendRequests' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat64], [], []),
    'markAllNotificationsAsRead' : IDL.Func([], [], []),
    'register' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeFriend' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'updateBio' : IDL.Func([IDL.Text], [], []),
    'updateCoverPhoto' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
    'updateProfilePhoto' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };