/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'createdAt' : bigint,
  'text' : string,
  'author' : Principal,
  'postId' : bigint,
}
export type ExternalBlob = Uint8Array;
export type MediaType = { 'video' : null } |
  { 'photo' : null };
export interface Notification {
  'id' : bigint,
  'notificationType' : NotificationType,
  'createdAt' : bigint,
  'read' : boolean,
  'user' : Principal,
  'relatedUser' : [] | [Principal],
  'postId' : [] | [bigint],
}
export type NotificationType = { 'newPostFromFriend' : null } |
  { 'friendRequestAccepted' : null } |
  { 'friendRequestReceived' : null };
export interface Post {
  'id' : bigint,
  'media' : ExternalBlob,
  'owner' : Principal,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'caption' : string,
  'mediaType' : MediaType,
}
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'createdAt' : bigint,
  'profilePhoto' : [] | [ExternalBlob],
  'coverPhoto' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptFriendRequest' : ActorMethod<[Principal], undefined>,
  'addComment' : ActorMethod<[bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllNotifications' : ActorMethod<[], undefined>,
  'createPost' : ActorMethod<[string, ExternalBlob, MediaType], bigint>,
  'declineFriendRequest' : ActorMethod<[Principal], undefined>,
  'deleteComment' : ActorMethod<[bigint, bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'editPost' : ActorMethod<[bigint, string], undefined>,
  'dismissNotification' : ActorMethod<[bigint], undefined>,
  'getAcceptedFriends' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getLikes' : ActorMethod<[bigint], Array<Principal>>,
  'getMainFeed' : ActorMethod<[], Array<Post>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPendingFriendRequests' : ActorMethod<[], Array<Principal>>,
  'getPostById' : ActorMethod<[bigint], Post>,
  'getPrincipalByUsername' : ActorMethod<[string], [] | [Principal]>,
  'getProfileByUsername' : ActorMethod<[string], [] | [UserProfile]>,
  'getProfilePosts' : ActorMethod<[Principal], Array<Post>>,
  'getSentFriendRequests' : ActorMethod<[], Array<Principal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUsernameAvailable' : ActorMethod<[string], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'markAllNotificationsAsRead' : ActorMethod<[], undefined>,
  'register' : ActorMethod<[string, string], undefined>,
  'removeFriend' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendFriendRequest' : ActorMethod<[Principal], undefined>,
  'updateBio' : ActorMethod<[string], undefined>,
  'updateCoverPhoto' : ActorMethod<[[] | [ExternalBlob]], undefined>,
  'updateProfilePhoto' : ActorMethod<[[] | [ExternalBlob]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];